@extends('layouts.header')

@section('content')
<div class="admin-request-page">
    <div class="admin-head"><a href="{{ url('account') }}"><i class="bi bi-arrow-left"></i></a><div><h1>Stock request approvals</h1><p>Approve requests to add stock to dealer inventories.</p></div></div>
    @if(session('success'))<div class="notice success">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="notice error">{{ $errors->first() }}</div>@endif
    <div class="request-board">
        <div class="board-title"><h2>Dealer requests</h2><span>{{ $requests->where('status', 'Pending')->count() }} pending</span></div>
        @forelse($requests as $request)
            <article class="admin-request"><div><strong>{{ optional($request->dealer)->name ?? 'Dealer #' . $request->dealer_id }}</strong><p>{{ optional(optional($request->dealer)->dealer)->store_name ?: 'Dealer account' }} · {{ optional($products->get($request->product_id))->product_name ?? 'Product #' . $request->product_id }} · <b>{{ number_format($request->quantity) }} units</b></p>@if($request->remarks)<small>Note: {{ $request->remarks }}</small>@endif</div><div class="approval-actions"><span class="status {{ strtolower($request->status) }}">{{ $request->status }}</span>@if($request->status === 'Pending')<form method="POST" action="{{ route('admin.stock.requests.approve', $request) }}">@csrf<button class="approve">Approve</button></form><button class="reject" type="button" onclick="rejectRequest({{ $request->id }})">Reject</button>@endif</div></article>
        @empty <div class="empty">No dealer stock requests yet.</div>@endforelse
    </div>
</div>
<form id="rejectForm" method="POST" class="reject-dialog">@csrf<input name="remarks" maxlength="500" required placeholder="Reason for rejection"><button>Reject request</button></form>
@endsection
@section('css')
<style>body{background:#eef4f8}.admin-request-page{max-width:980px;margin:0 auto;padding:28px 18px}.admin-head{display:flex;gap:14px;align-items:center;margin-bottom:20px}.admin-head a{width:42px;height:42px;border-radius:8px;background:#e8f7fc;color:#1688b3;display:grid;place-items:center}.admin-head h1{margin:0;font-size:23px}.admin-head p{margin:4px 0;color:#667085;font-size:13px}.request-board{background:white;border:1px solid #e8eef6;border-radius:12px;padding:18px}.board-title{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #edf2f7;padding-bottom:13px}.board-title h2{font-size:17px;margin:0}.board-title span{background:#fff7ed;color:#b45309;padding:5px 9px;border-radius:99px;font-size:12px;font-weight:800}.admin-request{display:flex;justify-content:space-between;gap:18px;padding:16px 4px;border-bottom:1px solid #edf2f7}.admin-request:last-child{border:0}.admin-request strong{color:#101828}.admin-request p,.admin-request small{margin:5px 0 0;color:#667085;font-size:13px}.approval-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.approval-actions form{margin:0}.approve,.reject,.reject-dialog button{border:0;border-radius:7px;padding:9px 12px;font-weight:800;cursor:pointer}.approve{background:#16834a;color:#fff}.reject{background:#fef2f2;color:#b42318}.status{padding:5px 9px;border-radius:99px;font-size:11px;font-weight:800}.status.pending{background:#fff7ed;color:#b45309}.status.approved{background:#ecfdf3;color:#16834a}.status.rejected{background:#fef2f2;color:#b42318}.notice{margin-bottom:14px;padding:12px;border-radius:8px;font-size:13px;font-weight:700}.success{background:#ecfdf3;color:#16834a}.error{background:#fef2f2;color:#b42318}.reject-dialog{display:none;position:fixed;z-index:9;left:50%;top:50%;transform:translate(-50%,-50%);padding:20px;background:#fff;border-radius:12px;box-shadow:0 15px 50px #0004}.reject-dialog.show{display:flex;gap:8px}.reject-dialog input{width:260px;padding:10px;border:1px solid #d9e4ef;border-radius:7px}@media(max-width:600px){.admin-request{flex-direction:column}.approval-actions{width:100%}}</style>
@endsection
@section('js')<script>function rejectRequest(id){const f=document.getElementById('rejectForm');f.action='{{ url('/admin/stock-requests') }}/'+id+'/reject';f.classList.add('show');f.querySelector('input').focus()}</script>@endsection
